# Generated by Django 6.1.1 on 2026-10-01 19:44

import uuid

from django.db import migrations, models


def rellenar_codigos_boleto(apps, schema_editor):
    item_orden = apps.get_model('ventas', 'ItemOrden')
    for item in item_orden.objects.filter(codigo_boleto__isnull=True).iterator():
        item.codigo_boleto = uuid.uuid4()
        item.save(update_fields=['codigo_boleto'])


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorden',
            name='codigo_boleto',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='Código único del boleto'),
        ),
        migrations.AddField(
            model_name='itemorden',
            name='documento_pasajero',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='RUT o pasaporte del ocupante'),
        ),
        migrations.AddField(
            model_name='itemorden',
            name='nombre_pasajero',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre completo del ocupante'),
        ),
        migrations.RunPython(
            rellenar_codigos_boleto,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='itemorden',
            name='codigo_boleto',
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                editable=False,
                null=True,
                unique=True,
                verbose_name='Código único del boleto',
            ),
        ),
    ]
