# Generated by Django 6.1.1 on 2026-10-01 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrito', '0001_initial'),
        ('transporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carro', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='itemcarro',
            name='asiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_carro', to='transporte.asiento', verbose_name='Asiento'),
        ),
        migrations.AddField(
            model_name='itemcarro',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carrito.carro', verbose_name='Carro'),
        ),
        migrations.AddConstraint(
            model_name='itemcarro',
            constraint=models.UniqueConstraint(fields=('carro', 'asiento'), name='unique_itemcarro_carro_asiento'),
        ),
    ]
