# Generated by Django 6.1.1 on 2026-10-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarro',
            name='documento_pasajero',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='RUT o pasaporte del ocupante'),
        ),
        migrations.AddField(
            model_name='itemcarro',
            name='nombre_pasajero',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre completo del ocupante'),
        ),
    ]
