# Generated by Django 6.1.1 on 2026-10-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='tipo',
            field=models.CharField(choices=[('SEMICAMA', 'Semicama'), ('CAMA', 'Cama')], default='SEMICAMA', max_length=10, verbose_name='Tipo de asiento'),
        ),
        migrations.AddField(
            model_name='bus',
            name='cantidad_cama',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de asientos cama'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='precio_cama',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tarifa cama'),
        ),
    ]
