# Generated by Django 6.1.1 on 2026-10-01 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_asiento_tipo_bus_cantidad_cama_servicio_precio_cama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio base'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio_cama',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarifa cama'),
        ),
        migrations.AddConstraint(
            model_name='bus',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_cama__lte', models.F('capacidad'))), name='cantidad_cama_no_supera_capacidad'),
        ),
    ]
